export const LOGIN_USER = 'LOGIN_USER' 

export const VALIDATE_PAYMENT = 'VALIDATE_PAYMENT'
export const MAKE_PAYMENT = 'MAKE_PAYMENT'
export const LOAD_WALLET = 'LOAD_WALLET'

//ERRORS
export const ERROR_LOAD = 'ERROR_LOAD'
export const ERROR_LOAD_CLEAR = 'ERROR_LOAD_CLEAR'
export const ERRORS_CLEAR = 'ERRORS_CLEAR'

export const CLEAR_ERROR = 'CLEAR_ERROR'
export const ERROR_LOGIN = 'ERROR_LOGIN'